### ISSUE TITLE
NPE & tree doesn't render

### ISSUE THREAD

**Issue by fsparv** [linux-china/zookeeper-intellij#11]
2014-12-11 16:50:19,772 [ 313270]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 13.1.6  Build #IU-135.1306 
2014-12-11 16:50:19,772 [ 313270]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
2014-12-11 16:50:19,772 [ 313270]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2014-12-11 16:50:19,773 [ 313271]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
2014-12-11 16:50:19,773 [ 313271]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2014-12-11 16:50:19,773 [ 313271]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowSettings 
2014-12-11 16:50:19,775 [ 313273]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
    at org.mvnsearch.intellij.plugin.zookeeper.ui.ZkNode.getTooltip(ZkNode.java:101)
    at org.mvnsearch.intellij.plugin.zookeeper.ZkProjectComponent$1.getTreeCellRendererComponent(ZkProjectComponent.java:119)
    at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2718)
    at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:475)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1342)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.getPreferredWidth(VariableHeightLayoutCache.java:1159)
    at javax.swing.tree.VariableHeightLayoutCache.getMaxNodeWidth(VariableHeightLayoutCache.java:990)
    at javax.swing.tree.VariableHeightLayoutCache.getPreferredWidth(VariableHeightLayoutCache.java:291)
    at javax.swing.plaf.basic.BasicTreeUI.updateCachedPreferredSize(BasicTreeUI.java:1821)
    at javax.swing.plaf.basic.BasicTreeUI.getPreferredSize(BasicTreeUI.java:1924)
    at javax.swing.plaf.basic.BasicTreeUI.getPreferredSize(BasicTreeUI.java:1912)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1642)
    at com.intellij.ui.treeStructure.Tree.getPreferredSize(Tree.java:813)
    at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:769)
    at java.awt.Container.layout(Container.java:1420)
    at java.awt.Container.doLayout(Container.java:1409)
    at java.awt.Container.validateTree(Container.java:1506)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validateTree(Container.java:1512)
    at java.awt.Container.validate(Container.java:1479)
    at javax.swing.RepaintManager$2.run(RepaintManager.java:698)
    at javax.swing.RepaintManager$2.run(RepaintManager.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:695)
    at com.intellij.ide.IdeRepaintManager.validateInvalidComponents(IdeRepaintManager.java:114)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1679)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by sailonthrough** [comment]
I hava the same question,is there any solution?

**Comment by sailonthrough** [comment]
I guess the zookeeper version is too high
